### ISSUE TITLE
Explanation Dashboard for local explanation throwing KeyError - "intercept"

### ISSUE THREAD

**Issue by nagapavannukala** [interpretml/interpret-community#260]
**Describe the bug**
I tried to display the Explanation Dashboard for local explanation on my local Windows system. It's throwing a KeyError "intercept" pointing to "explanation_dashboard_input.py" from "widget" module.

**Expected behavior**
I should be getting the Dashboard displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/43603287/84742501-23fb0a80-afce-11ea-9e17-f62ccb527dd3.png)

**Comment by imatiach-msft** [comment]
@nagapavannukala sorry about the issue you are encountering, and sorry about the late reply.  Could you give us more details about this issue?  What explainer did you use that caused this error?  If the dataset is not private, would you be able to share an example that reproduces this issue?

**Comment by xiaolul** [comment]
I have the same problem when trying to produce the local explanation based on Azure AutoML output.  Dataset is the "orange juice store" sample data used in the forecasting notebook. I setup the MimicWrapper as per introduced in the AutoML explain page.
It works perfectly with the global explain, but not as expected for the local. Individual feature importance can be obtained in the json format, but I am not able to visualize it:
- If I try to call dashboard, I got the following error (it also throws error when I pass the fitted model parameter)
```python
from interpret_community.widget import ExplanationDashboard
ExplanationDashboard(engineered_local_explainations, datasetX=automl_explainer_setup_obj.X_test_transform)
```
- I also cannot call `engineered_local_explainations.visualize()` method since it doesn't support "DynamicLocalExplain`.

So, what is the best way of viz the local explanation?

**Comment by imatiach-msft** [comment]
@nagapavannukala @xiaolul @saimachi @konabuta I've sent a PR to fix this issue here:
https://github.com/interpretml/interpret-community/pull/387
