### ISSUE TITLE
Information about the Local Explanations by the Mimic Explainer

### ISSUE THREAD

**Issue by Mahima-ai** [interpretml/interpret-community#399]
Hey there,

I studied the Mimic Explainer Literature as given in [Global Surrogate Models](https://christophm.github.io/interpretable-ml-book/global.html). I would like to have clarity on how the Azure's Mimic Explainer interprets the local explanation. Does it uses LIME or SHAP to interpret the local model, if yes then what are the inputs to these methods?

Thanks.

**Comment by imatiach-msft** [comment]
hi @Mahima-ai , the mimic explainer has several surrogate models.  We usually use the lightgbm surrogate model by default for dense data and the linear surrogate model for sparse data in most customer scenarios.  To get local explanations, after training the surrogate model, we run SHAP TreeExplainer for lightgbm surrogate model (which is much faster than KernelExplainer, especially as the number of features increases) and LinearExplainer for the linear surrogate model.  SHAP's TreeExplainer for lightgbm models is actually implemented inside lightgbm, it is an optimized native implementation in C++, and during extensive testing/benchmarking we found it to outperform by far all other explainers in both speed and accuracy.  However, since we are training a surrogate model, there will be some loss in the accuracy of the explanations (note KernelExplainer is also an approximation as the number of features increases but the number of samples stays constant).  Unfortunately, in most production use-cases the blackbox KernelExplainer took too long or ran into various issues we couldn't resolve, so mimic explainer has become our de-facto explainer currently.

**Comment by Mahima-ai** [comment]
Hi @imatiach-msft  Thanks for the instant response with a great explanation.

**Comment by imatiach-msft** [comment]
closing the informational questions
