### ISSUE TITLE
Is interpret-community not compatible with interpret v0.2.5?

### ISSUE THREAD

**Issue by bwang482** [interpretml/interpret-community#422]
I have `interpret` v0.2.5 installed on a Windows 10 machine with Python 3.7 env then I installed `interpret-community`. I found `interpret` gone back to v0.2.4 so I updated it to v0.2.5 again. Now I can't import `interpret-community` anymore. 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-7c6318f93b40> in <module>
----> 1 from interpret.ext.blackbox import TabularExplainer

ImportError: cannot import name 'TabularExplainer' from 'interpret.ext.blackbox' (d:\srp\lib\site-packages\interpret\ext\blackbox\__init__.py)
```

**Comment by bwang482** [comment]
This is the error message I get when installing `raiwidgets`:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
interpret 0.2.5 requires interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]>=0.2.5, but you have interpret-core 0.2.4 which is incompatible.
```

**Comment by imatiach-msft** [comment]
@bwang482 it looks like interpret 0.2.5 was just released on June 21.  I will try to upgrade to it this week.  We have had breaking changes in the past so we manually upgrade to new interpret releases.  In all likelihood it should just work anyway.  You can use the older version of interpret for now, or you can force pip to install the newer version of interpret but the import in interpret-community will break.  You can still use:
```
from interpret_community import TabularExplainer
```
instead of the other import.  You can also just try to update this upper bound on master and install locally, as long as there are no breaking changes it should work:

https://github.com/interpretml/interpret-community/blob/master/python/setup.py#L44

**Comment by imatiach-msft** [comment]
closing as this is fixed with PR:
https://github.com/interpretml/interpret-community/pull/423
