### ISSUE TITLE
 ImportError: cannot import name 'TabularExplainer'

### ISSUE THREAD

**Issue by Hiramdu** [interpretml/interpret-community#460]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-af69664ae144> in <module>
      6 #from interpret.ext.blackbox import TabularExplainer
      7 #from interpret.ext.blackbox import *
----> 8 from interpret.ext.blackbox import TabularExplainer
      9 
     10 # OR

ImportError: cannot import name 'TabularExplainer'

**Comment by imatiach-msft** [comment]
@Hiramdu this has happened several times before and it's usually due to dependency issues:

https://github.com/interpretml/interpret-community/issues/422
https://github.com/interpretml/interpret-community/issues/406
https://github.com/interpretml/interpret-community/issues/349

Do you see any errors when installing interpret-community package?
If you can't use the extension system, then you can try importing from interpret_community directly, for example:

```
from interpret_community.tabular_explainer import TabularExplainer
```

**Comment by imatiach-msft** [comment]
closing this issue as it's usually an environment problem which has happened several times before and I haven't heard back

**Comment by VasundharaAcharya** [comment]
> @Hiramdu this has happened several times before and it's usually due to dependency issues:
> 
> #422 #406 #349
> 
> Do you see any errors when installing interpret-community package? If you can't use the extension system, then you can try importing from interpret_community directly, for example:
> 
> ```
> from interpret_community.tabular_explainer import TabularExplainer
> ```
This one actually solves the problem. Thanks.
